# Generated by Django 4.2.4 on 2023-09-04 07:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('author_and_book', '0002_authormodel_bio_en_authormodel_bio_ru_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='authormodel',
            name='country_en',
        ),
        migrations.RemoveField(
            model_name='authormodel',
            name='country_ru',
        ),
        migrations.RemoveField(
            model_name='authormodel',
            name='country_uz',
        ),
    ]
